// Generated by CoffeeScript 1.3.2
(function() {
  'use strict';

  angular.module('blog', []).config([
    '$routeProvider', function(routeProvider) {
      routeProvider.when('/home', {
        template: 'partials/home.html',
        controller: HomeController
      });
      routeProvider.when('/about', {
        template: 'partials/about.html'
      });
      return routeProvider.otherwise({
        redirectTo: '/home'
      });
    }
  ]);

}).call(this);
