// Generated by CoffeeScript 1.3.2
(function() {
  var partial,
    __slice = [].slice;

  partial = function() {
    var a, func;
    func = arguments[0], a = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return function() {
      var b;
      b = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return func.apply(null, __slice.call(a).concat(__slice.call(b)));
    };
  };

}).call(this);
